# compose 파일 버전
version: "3"
services:
  # 서비스 명
  mongodb:
    # 사용할 이미지
    image: mongo
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너명 설정
    container_name: mongo
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "27017:27017"

    # 볼륨 설정
    volumes:
      - ./data/mongodb:/data/db

  server:
    build: .
    ports:
      - "8070:8070"
    depends_on:
      - mongodb
